{{- if .Values.discourse.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Values.argocd.project }}-discourse
  namespace: {{ .Values.argocd.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "5"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: {{ .Values.argocd.project }}
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
  destination:
    name: in-cluster
    namespace: {{ .Values.argocd.project }}
  source:
    chart: discourse
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: 11.0.0
    helm:
      releaseName: discourse
      values: |
        persistence:
          enabled: true
          size: 5Gi
        ingress:
          enabled: true
          hostname: "discourse.{{ .Values.global.domain }}"
          ingressClassName: nginx
          annotations:
            cert-manager.io/cluster-issuer: letsencrypt-prod
            external-dns.alpha.kubernetes.io/target: "{{ .Values.global.env }}-humble-tunnel.{{ .Values.global.domain }}"
            external-dns.alpha.kubernetes.io/cloudflare-proxied: "true"
            nginx.ingress.kubernetes.io/enable-cors: "true"
            nginx.ingress.kubernetes.io/cors-allow-origin: "*"
          extraHosts:
            - host: &host discourse.{{ .Values.global.domain }}
              paths:
                - path: /
                  pathType: Prefix
          extraTls:
            - secretName: discourse-tls-certificate
              hosts:
                - *host
{{- end }}
