{{- if .Values.jellyfin.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Values.argocd.project }}-jellyfin
  namespace: {{ .Values.argocd.namespace }}
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: {{ .Values.argocd.project }}
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
  destination:
    name: in-cluster
    namespace: apps
  source:
    repoURL: https://bjw-s.github.io/helm-charts 
    chart: app-template
    targetRevision: 2.5.0
    helm:
      releaseName: jellyfin
      values: |
        defaultPodOptions:
          securityContext:
            fsGroup: 1000
        controllers:
          main:
            containers:
              main:
                image:
                  repository: docker.io/jellyfin/jellyfin
                  tag: 10.8.13
              transmission:
                image:
                  repository: lscr.io/linuxserver/transmission
                  tag: 4.0.5
              prowlarr:
                image:
                  repository: lscr.io/linuxserver/prowlarr
                  tag: 1.11.4
              radarr:
                image:
                  repository: lscr.io/linuxserver/radarr
                  tag: 5.2.6
              sonarr:
                image:
                  repository: lscr.io/linuxserver/sonarr
                  tag: 4.0.0
              jellyseerr:
                image:
                  repository: docker.io/fallenbagel/jellyseerr
                  tag: 1.7.0
              bazarr:
                image:
                  repository: lscr.io/linuxserver/bazarr
                  tag: 1.4.0
        service:
          main:
            ports:
              http:
                port: 8096
                protocol: HTTP
              transmission:
                port: 9091
                protocol: HTTP
              prowlarr:
                port: 9696
                protocol: HTTP
              radarr:
                port: 7878
                protocol: HTTP
              sonarr:
                port: 8989
                protocol: HTTP
              jellyseerr:
                port: 5055
                protocol: HTTP
              bazarr:
                port: 6767
                protocol: HTTP
        ingress:
          main:
            enabled: true
            className: nginx
            annotations:
              cert-manager.io/cluster-issuer: letsencrypt-prod
            hosts:
              - host: &jellyfinHost jellyfin.{{ .Values.global.domain }}
                paths:
                  - path: /
                    pathType: Prefix
                    service:
                      name: main
                      port: http
              - host: &transmissionHost transmission.{{ .Values.global.domain }}
                paths:
                  - path: /
                    pathType: Prefix
                    service:
                      name: main
                      port: transmission
              - host: &prowlarrHost prowlarr.{{ .Values.global.domain }}
                paths:
                  - path: /
                    pathType: Prefix
                    service:
                      name: main
                      port: prowlarr
              - host: &radarrHost radarr.{{ .Values.global.domain }}
                paths:
                  - path: /
                    pathType: Prefix
                    service:
                      name: main
                      port: radarr
              - host: &sonarrHost sonarr.{{ .Values.global.domain }}
                paths:
                  - path: /
                    pathType: Prefix
                    service:
                      name: main
                      port: sonarr
              - host: &jellyseerrHost jellyseerr.{{ .Values.global.domain }}
                paths:
                  - path: /
                    pathType: Prefix
                    service:
                      name: main
                      port: jellyseerr
              - host: &bazarrHost bazarr.{{ .Values.global.domain }}
                paths:
                  - path: /
                    pathType: Prefix
                    service:
                      name: main
                      port: bazarr

            tls:
              - secretName: jellyfin-tls-certificate
                hosts:
                  - *jellyfinHost
                  - *transmissionHost
                  - *prowlarrHost
                  - *radarrHost
                  - *sonarrHost
                  - *jellyseerrHost
                  - *bazarrHost
        persistence:
          config:
            enabled: true
            storageClass: "longhorn"
            accessMode: ReadWriteOnce
            size: 70Gi
            advancedMounts:
              main:
                main:
                  - path: /config
                    subPath: jellyfin/config
                  - path: /media/movies
                    subPath: movies
                  - path: /media/shows
                    subPath: shows
                transmission:
                  - path: /config
                    subPath: transmission/config
                  - path: /downloads
                    subPath: transmission/downloads
                prowlarr:
                  - path: /config
                    subPath: prowlarr/config
                radarr:
                  - path: /config
                    subPath: radarr/config
                  - path: /downloads/complete
                    subPath: transmission/downloads/complete
                  - path: /movies
                    subPath: movies
                sonarr:
                  - path: /config
                    subPath: sonarr/config
                  - path: /downloads/complete
                    subPath: transmission/downloads/complete
                  - path: /shows
                    subPath: shows
                jellyseerr:
                  - path: /app/config
                    subPath: jellyseerr/config
                bazarr:
                  - path: /config
                    subPath: bazarr/config
                  - path: /media/movies
                    subPath: movies
                  - path: /media/shows
                    subPath: shows
{{- end }}
