# Override value for production
kanidm:
  enabled: true
  namespace: kanidm

dex:
  enabled: true

externalSecrets:
  enabled: true

secretGenerator:
  enabled: true

temporal:
  enabled: false

cassandra:
  enabled: false

coroot:
  enabled: true
