{{- if .Values.runnerController.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Values.argocd.project }}-runner-controller
  namespace: {{ .Values.argocd.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: {{ .Values.argocd.project }}
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
  destination:
    name: in-cluster
    namespace: {{ .Values.runnerController.namespace }}
  source:
    chart: actions-runner-controller
    repoURL: https://actions-runner-controller.github.io/actions-runner-controller
    targetRevision: 0.20.2
    helm:
      releaseName: actions-runner-controller
      values: |
        authSecret:
          name: action-runner-secret
        syncPeriod: 5m
{{- end }}
