{{ if .Values.cassandra.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Values.argocd.project }}-cassandra
  namespace: {{ .Values.argocd.namespace }}
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: {{ .Values.argocd.project }}
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
  destination:
    name: in-cluster
    namespace: platform
  source:
    chart: cassandra
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: 11.3.14
    helm:
      releaseName: cassandra
      values: |
        dbUser:
          user: cassandra
          existingSecret: "temporal-cassandra"
        replicaCount: 1
        persistence:
          enabled: false
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: temporal-cassandra
  namespace: platform
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: global-secrets
  target:
    name: temporal-cassandra
  data:
    - secretKey: cassandra-password
      remoteRef:
        key: temporal.cassandra
        property: cassandra-password
    - secretKey: password
      remoteRef:
        key: temporal.cassandra
        property: cassandra-password
{{- end }}
