{{- if .Values.globalSecrets.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Values.argocd.project }}-global-secrets
  namespace: {{ .Values.argocd.namespace }}
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: {{ .Values.argocd.project }}
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
  destination:
    name: in-cluster
    namespace: global-secrets
  source:
    chart: secret-generator
    repoURL: ghcr.io/locmai
    targetRevision: 0.1.10
    helm:
      releaseName: global-secrets
      values: |
        config:
          - name: dex.grafana
            data:
              - key: client_secret
                length: 32
          - name: dex.argocd
            data:
              - key: client_secret
                length: 32
          - name: dex.oauth2proxy
            data:
              - key: client_secret
                length: 32
              - key: cookie_secret
                length: 16
          - name: temporal.cassandra
            data:
              - key: cassandra-password
                length: 32
                special: false
{{- end }}
