{{- if .Values.reloader.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Values.argocd.project }}-reloader
  namespace: {{ .Values.argocd.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: {{ .Values.argocd.project }}
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
  destination:
    name: in-cluster
    namespace: {{ .Values.reloader.namespace }}
  source:
    chart: reloader
    repoURL: https://stakater.github.io/stakater-charts
    targetRevision: v0.0.128
    helm:
      releaseName: reloader
      values: |
        dummy: true
{{- end }}
