# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "kubernetes" {
    config_path   = "/home/locmai/Workspace/humble/metal/kubeconfig.prod.yaml"
    secret_suffix = "tfstate"
  }
}
