apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: cert-manager
  namespace: "cert-manager"
  labels:
    app: cert-manager
    app.kubernetes.io/name: cert-manager
    app.kubernetes.io/instance: cert-manager
    app.kubernetes.io/component: "controller"
    prometheus: default
spec:
  jobLabel: cert-manager
  selector:
    matchLabels:
      app.kubernetes.io/name: cert-manager
      app.kubernetes.io/instance: cert-manager
      app.kubernetes.io/component: "controller"
  namespaceSelector:
    matchNames:
      - cert-manager
  endpoints:
  - targetPort: 9402
    path: /metrics
    interval: 60s
    scrapeTimeout: 30s
