{{- if .Values.certmanager.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Values.argocd.project }}-cert-manager
  namespace: {{ .Values.argocd.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "0"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: {{ .Values.argocd.project }}
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
  destination:
    name: in-cluster
    namespace: {{ .Values.certmanager.namespace }}
  source:
    chart: cert-manager
    repoURL: https://charts.jetstack.io
    targetRevision: v1.9.1
    helm:
      releaseName: cert-manager
      values: |
        installCRDs: true

        prometheus:
          enabled: true
          servicemonitor:
            enabled: true
{{- end }}
