{{- if .Values.mimir.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Values.argocd.project }}-mimir
  namespace: {{ .Values.argocd.namespace }}
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: {{ .Values.argocd.project }}
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
  destination:
    name: in-cluster
    namespace: {{ .Values.mimir.namespace }}
  source:
    chart: mimir-distributed
    repoURL: https://grafana.github.io/helm-charts
    targetRevision: 5.3.0
    helm:
      releaseName: mimir
      values: |
        alertmanager:
          enabled: false
          persistentVolume:
            enabled: true
          replicas: 2
          resources:
            limits:
              memory: 1.4Gi
            requests:
              cpu: 1
              memory: 1Gi
          statefulSet:
            enabled: true

        compactor:
          replicas: 3
          persistentVolume:
            size: 5Gi
          resources:
            requests:
              cpu: 10m
              memory: 50Mi

        distributor:
          replicas: 2
          resources:
            limits:
              memory: 2Gi
            requests:
              cpu: 1
              memory: 1Gi
          extraArgs:
            'distributor.ingestion-rate-limit': "10000000"
            'distributor.ingestion-burst-size': "20000000"

        ingester:
          persistentVolume:
            size: 5Gi
          replicas: 3
          resources:
            requests:
              cpu: 10m
              memory: 512Mi
          extraArgs:
            'ingester.max-global-series-per-user': "20000000"

        chunks-cache:
          enabled: true
          replicas: 1

        index-cache:
          enabled: true
          replicas: 1

        metadata-cache:
          enabled: true
          replicas: 1

        results-cache:
          enabled: true
          replicas: 1

        minio:
          enabled: true
          mode: standalone
          rootUser: grafana-mimir
          buckets:
            - name: mimir-tsdb
              policy: none
              purge: false
            - name: mimir-ruler
              policy: none
              purge: false
            - name: enterprise-metrics-tsdb
              policy: none
              purge: false
            - name: enterprise-metrics-admin
              policy: none
              purge: false
            - name: enterprise-metrics-ruler
              policy: none
              purge: false
          persistence:
            size: 30Gi
        querier:
          replicas: 1
          resources:
            requests:
              cpu: 10m
              memory: 128Mi

        query_frontend:
          replicas: 1
          resources:
            limits:
              memory: 2.8Gi
            requests:
              cpu: 2
              memory: 2Gi

        ruler:
          enabled: true
          replicas: 1
          resources:
            requests:
              cpu: 10m
              memory: 128Mi

        store_gateway:
          persistentVolume:
            size: 2Gi
          replicas: 2
          resources:
            requests:
              cpu: 10m
              memory: 50Mi

        nginx:
          enabled: true
          replicas: 1
{{- end }}
