{{- if .Values.monitoring.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Values.argocd.project }}-monitoring
  namespace: {{ .Values.argocd.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "0"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: {{ .Values.argocd.project }}
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
  destination:
    name: in-cluster
    namespace: {{ .Values.monitoring.namespace }}
  source:
    chart: kube-prometheus-stack
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 41.9.0
    helm:
      releaseName: monitoring
      values: |
        prometheus:
          prometheusSpec:
            replicas: 1
            ruleSelectorNilUsesHelmValues: false
            serviceMonitorSelectorNilUsesHelmValues: false
            probeSelectorNilUsesHelmValues: false
            podMonitorSelectorNilUsesHelmValues: false
            serviceMonitorNamespaceSelector: {}
            podMonitorNamespaceSelector: {}

            # https://github.com/prometheus-community/helm-charts/issues/2506#issuecomment-1304632868
            # enableFeatures:
            # - agent
            containers:
            - name: prometheus
              env:
              - name: JAEGER_AGENT_PORT
                value: "5755"
            storageSpec:
              volumeClaimTemplate:
                spec:
                  storageClassName: longhorn
                  accessModes: ["ReadWriteOnce"]
                  resources:
                    requests:
                      storage: 2Gi
            remoteWrite:
              - url: http://mimir-nginx/api/v1/push
                headers:
                  X-Scope-OrgID: humble
          server:
            enableServiceLinks: false

        prometheusOperator:
          admissionWebhooks:
            enabled: false
            failurePolicy: Ignore
            patch:
              enabled: false
          tls:
            enabled: false
          denyNamespaces:
            - 'notreal'
        grafana:
          enabled: true
          replicas: 1
          enableServiceLinks: false
          env:
            JAEGER_AGENT_PORT: '5755'
          image:
            tag: 8.2.6
          envFromSecret: "humble-oidc-secrets"
          persistence:
            enabled: false
          ingress:
            enabled: false
          grafana.ini:
            server:
              domain: "grafana.{{ .Values.global.domain }}"
              root_url: "https://%(domain)s/"
            auth:
              disable_login_form: false
            auth.generic_oauth:
              name: Vault
              enabled: true
              allow_sign_up: true
              client_id: "\"${OIDC_CLIENT_ID}\""
              client_secret: "\"${OIDC_CLIENT_SECRET}\""
              scopes: openid groups user email
              auth_url: "https://auth.maibaloc.com/ui/vault/identity/oidc/provider/vault-provider/authorize"
              token_url: "https://auth.maibaloc.com/v1/identity/oidc/provider/vault-provider/token"
              api_url: "https://auth.maibaloc.com/v1/identity/oidc/provider/vault-provider/userinfo"
          sidecar:
            enableUniqueFilenames: false
            image:
              repository: omegavveapon/kopf-k8s-sidecar
              tag: 1.3.4
            dashboards:
              enabled: true
              label: grafana_dashboard
              folder: /tmp/dashboards
              searchNamespace: {{ .Values.monitoring.namespace }}
              provider:
                allowUiUpdates: false
                foldersFromFilesStructure: true
              annotations:
                k8s-sidecar-target-directory: "/tmp/dashboards/kubernetes"
            datasources:
              defaultDatasourceEnabled: false
          additionalDataSources:
            - name: loki
              type: loki
              editable: false
              url: http://loki-stack:3100
              isDefault: false
            - name: Mimir
              isDefault: true
              type: prometheus
              url: http://mimir-nginx/prometheus
              basicAuth: false
              jsonData:
                httpHeaderName1: X-Scope-OrgID
              secureJsonData:
                httpHeaderValue1: humble
          plugins:
          - yesoreyeram-boomtheme-panel
          - flant-statusmap-panel
          - vonage-status-panel
          - natel-discrete-panel
          - grafana-polystat-panel
          - digiapulssi-breadcrumb-panel
          - macropower-analytics-panel

        alertmanager:
          enabled: false
          config:
            global:
              resolve_timeout: 5m
            route:
              group_by: ['alertname', 'job', 'ops']
              group_wait: 30s
              group_interval: 5m
              repeat_interval: 2h
              receiver: "yutaops-webhook"
              routes:
              - match:
                  ops: yuta
                receiver: 'yutaops-webhook'
              - match:
                  ops: argo-events
                receiver: 'argo-eventsource'
            receivers:
            - name: 'yutaops-webhook'
              webhook_configs:
                - url: 'http://yutaops-webhook.apps.svc.cluster.local:8501/webhook'
            - name: 'argo-eventsource'
              webhook_configs:
                - url: 'http://webhook-demo-eventsource-svc.argoworkflow.svc.cluster.local:12000/demo'
{{- end }}
