{{- if .Values.monitoring.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Values.argocd.project }}-monitoring
  namespace: {{ .Values.argocd.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "0"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: {{ .Values.argocd.project }}
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
  destination:
    name: in-cluster
    namespace: {{ .Values.monitoring.namespace }}
  source:
    chart: kube-prometheus-stack
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 43.3.1
    helm:
      releaseName: monitoring
      values: |
        prometheus:
          prometheusSpec:
            replicas: 1
            ruleSelectorNilUsesHelmValues: false
            serviceMonitorSelectorNilUsesHelmValues: false
            probeSelectorNilUsesHelmValues: false
            podMonitorSelectorNilUsesHelmValues: false
            serviceMonitorNamespaceSelector: {}
            podMonitorNamespaceSelector: {}

            # https://github.com/prometheus-community/helm-charts/issues/2506#issuecomment-1304632868
            # enableFeatures:
            # - agent
            containers:
            - name: prometheus
              env:
              - name: JAEGER_AGENT_PORT
                value: "5755"
            storageSpec:
              volumeClaimTemplate:
                spec:
                  storageClassName: longhorn
                  accessModes: ["ReadWriteOnce"]
                  resources:
                    requests:
                      storage: 10Gi
          server:
            enableServiceLinks: false

        prometheusOperator:
          admissionWebhooks:
            enabled: false
            failurePolicy: Ignore
            patch:
              enabled: false
          tls:
            enabled: false
          denyNamespaces:
            - 'notreal'
        grafana:
          enabled: true
          replicas: 1
          enableServiceLinks: false
          env:
            JAEGER_AGENT_PORT: '5755'
          envFromSecret: "humble-oidc-secrets"
          persistence:
            enabled: false
          ingress:
            enabled: false
          grafana.ini:
            security:
              disable_initial_admin_creation: true
            server:
              domain: "grafana.{{ .Values.global.domain }}"
              root_url: "https://%(domain)s/"
            auth:
              disable_login_form: false
            auth.generic_oauth:
              name: Vault
              enabled: true
              allow_sign_up: true
              client_id: "\"${OIDC_CLIENT_ID}\""
              client_secret: "\"${OIDC_CLIENT_SECRET}\""
              scopes: openid groups user email
              auth_url: "https://auth.{{ .Values.global.domain }}/ui/vault/identity/oidc/provider/vault-provider/authorize"
              token_url: "https://auth.{{ .Values.global.domain }}/v1/identity/oidc/provider/vault-provider/token"
              api_url: "https://auth.{{ .Values.global.domain }}/v1/identity/oidc/provider/vault-provider/userinfo"
              role_attribute_path: "contains(info.roles[*], 'admin') && 'Admin' || 'Admin'"
          sidecar:
            enableUniqueFilenames: false
            image:
              repository: omegavveapon/kopf-k8s-sidecar
              tag: 1.3.4
            dashboards:
              enabled: true
              label: grafana_dashboard
              folder: /tmp/dashboards
              searchNamespace: {{ .Values.monitoring.namespace }}
              provider:
                allowUiUpdates: false
                foldersFromFilesStructure: true
              annotations:
                k8s-sidecar-target-directory: "/tmp/dashboards/kubernetes"
          additionalDataSources:
            - name: loki
              type: loki
              editable: false
              url: http://loki-stack:3100
              isDefault: false
            - name: default
              type: prometheus
              editable: false
              url: http://monitoring-kube-prometheus-prometheus.observability:9090/
              isDefault: false
        alertmanager:
          enabled: false
{{- end }}
